### PR TITLE
fix: remove user-facing Atmo mentions

### LINKED ISSUE #361: Remove Atmo mentions
@flaki noticed that Subo mentions Atmo to users when it [lists available commands](https://github.com/suborbital/subo/blob/3bdb983c9f8b253eb6356f56cad1f1ee628368e2/subo/command/dev.go) and [at the root](https://github.com/suborbital/subo/blob/3bdb983c9f8b253eb6356f56cad1f1ee628368e2/root.go). We can either:

- Do a 1:1 name change
- Remove the reference entirely

The second option seems to me to be most in line with our new positioning, so I'm starting with that approach. 😊

### PR DESCRIPTION
**Pull request by LauraLangdon**
Closes #361. I just removed the mentions to Atmo rather than replacing them, but could do the opposite if that would be preferred ofc!

### CODE REVIEW

File: root.go [hunk 1]
```diff
@@ -13,8 +13,8 @@ func rootCommand() *cobra.Command {
 		Use:     "subo",
 		Short:   "Suborbital Development Platform CLI",
 		Version: release.Version(),
-		Long: `Subo is the full toolchain for using and managing Suborbital Development Platform tools,
-including building WebAssembly Runnables and Atmo projects.`,
+		Long: `Subo is the full toolchain for using and managing Suborbital
+Development Platform tools.`,
```
Comment (cohix) [inline root.go:17]: I don't think we need the linebreak here, and 'Suborbital Development Platform' can be replaced with 'Suborbital Extension Engine'

File: subo/command/dev.go [hunk 2]
```diff
@@ -16,8 +16,8 @@ import (
 func DevCmd() *cobra.Command {
 	cmd := &cobra.Command{
 		Use:   "dev",
-		Short: "run a development Atmo server using Docker",
-		Long:  `run a development Atmo server using Docker`,
+		Short: "run a development  server using Docker",
```
Comment (cohix) [inline subo/command/dev.go:19]: I think there's an extra space here

File: subo/command/dev.go [hunk 3]
```diff
@@ -54,8 +54,9 @@ func DevCmd() *cobra.Command {
 		},
 	}
 
-	cmd.Flags().String("port", "8080", "set the port that Atmo serves on")
-	cmd.Flags().BoolP("verbose", "v", false, "run Atmo with debug level logging")
+	cmd.Flags().String("port", "8080",
+		"set the port on which to serve the project")
```
Comment (cohix) [inline subo/command/dev.go:58]: extra linebreak?

**Review by ospencer — APPROVED** [review]
