### PR TITLE
fix: Prefer `docker compose` to `docker-compose`

### LINKED ISSUE #344: Subo should support systems with docker compose (v2)
I installed Docker [from the repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository) on Ubuntu, side-stepping Docker Desktop, and so I only have `docker-compose-plugin` which is the new `docker compose` (note the space).

> The docker compose (with a space) is a newer project to migrate compose to Go with the rest of the docker project. This is the v2 branch of the [docker/compose](https://github.com/docker/compose/tree/v2) repo. It's been first introduced to Docker Desktop users, so docker users on Linux didn't see the command. In addition to migrating to Go, it uses the compose-spec, and part of the rewrite may result in behavior differences.

Apparently [this is the way of the future](https://stackoverflow.com/a/66526176), and `subo compute deploy core --local` currently fails with an error, not being able to find the old `docker-compose` command:

```
⏩ START: preparing deployment
ℹ️  using cached environment token
✅ DONE: ready to start installation
⏩ START: installing...
sh: 1: docker-compose: not found
Error: 🚫 failed to docker-compose up: failed to Run command: exit status 127
Usage:
  subo compute deploy core [flags]
```

Because `alias`-es don't work with subo, one actually needs to create a [shell shim](https://askubuntu.com/a/955919) that re-maps `docker-compose` to `docker compose` (and that works because `up` is the same in both CLI-s), but this is a hassle and is undocumented, so we should at least document it, but it would be better fixing it in `subo` itself.

### PR DESCRIPTION
**Pull request by callahad**
Compose v2 is the future, but it may not be present on all installs.

This PR prefers `docker compose` but falls back to `docker-compose` if Compose v2 is not detected.

Alternative to #353

Fixes #344

### CODE REVIEW

**Comment by callahad** [comment]
(I suspect my Go may not be idiomatic here.)

The Compose v2 plugin should be present on all Docker Desktop installations updated in the last 18 months. It's most likely to be missing for Linux users who installed the Docker engine directly and accidentally missed the separate `docker-compose-plugin` package. The right answer is for them to install the plugin... but some proportion of those folks are likely to still have the legacy `docker-compose` script on their systems, and this PR would make things Just Work for them.

...but it's much simpler to just use Compose v2 directly and encourage people to install the plugin if it fails.

File: subo/command/compute_deploy_core.go [hunk 1]
```diff
@@ -129,11 +130,27 @@ func ComputeDeployCoreCommand() *cobra.Command {
...
+					// See: https://github.com/containerd/nerdctl/issues/1368
+					compose = "docker compose"
 				}
 
-				util.LogInfo("use `docker ps` and `docker-compose logs` to check deployment status")
+				command := fmt.Sprintf("%s up -d", compose)
+
+				if _, err := util.Command.Run(command); err != nil {
+					util.LogInfo("Is Docker Compose installed? https://docs.docker.com/compose/install/")
+					return errors.Wrap(err, "🚫 failed to run `docker compose up`")
```
Comment (cohix) [inline subo/command/compute_deploy_core.go:150]: I would put the _actual_ command that was run in the error message

**Comment by flaki** [comment]
LGTM, would def prefer this to #353

File: subo/command/compute_deploy_core.go [hunk 2]
```diff
@@ -129,11 +130,27 @@ func ComputeDeployCoreCommand() *cobra.Command {
...
 
-				util.LogInfo("use `docker ps` and `docker-compose logs` to check deployment status")
+				command := fmt.Sprintf("%s up -d", compose)
+
+				if _, err := util.Command.Run(command); err != nil {
+					util.LogInfo("Is Docker Compose installed? https://docs.docker.com/compose/install/")
+					return errors.Wrapf(err, "🚫 failed to run `%s`", command)
+				}
+
+				util.LogInfo("use `docker ps` and `docker compose logs` to check deployment status")
```
Comment (javorszky) [inline subo/command/compute_deploy_core.go:153]: this line should also use whatever the `compose` variable is.
```suggestion
				util.LogInfo(fmt.Sprintf("use `docker ps` and `%s logs` to check deployment status", compose))
```

File: subo/command/compute_deploy_core.go [hunk 3]
```diff
@@ -179,7 +196,7 @@ func ComputeDeployCoreCommand() *cobra.Command {
 	cmd.Flags().String(branchFlag, "main", "git branch to download templates from")
 	cmd.Flags().String(versionFlag, release.SCCTag, "Docker tag to use for control plane images")
 	cmd.Flags().Int(proxyPortFlag, proxyDefaultPort, "port that the Editor proxy listens on")
-	cmd.Flags().Bool(localFlag, false, "deploy locally using docker-compose")
+	cmd.Flags().Bool(localFlag, false, "deploy locally using docker compose")
```
Comment (javorszky) [inline subo/command/compute_deploy_core.go:199]: Should also maybe use whatever the code decided above docker-compose to be? Though that might mean that we might need to move the code to determine whether the system has docker-compose or docker compose available to be outside / before the `if localInstall` branch.

**Review by javorszky — CHANGES_REQUESTED** [review]
I think some additional refinements can be made with logging to user if we're determining which one to use.

File: subo/command/compute_deploy_core.go (hunk 3 above)
Comment (callahad) [reply subo/command/compute_deploy_core.go:199]: Or I could just use the proper noun version 😉 

```suggestion
	cmd.Flags().Bool(localFlag, false, "deploy locally using Docker Compose")
```

Comment (callahad) [reply subo/command/compute_deploy_core.go:199]: This is such a niche case I'm inclined to actually do that

Comment (callahad) [reply subo/command/compute_deploy_core.go:199]: ...and there's precedent up on line 39:

    Long:  `deploy the Suborbital Compute Core using Kubernetes or Docker Compose`

Comment (javorszky) [reply subo/command/compute_deploy_core.go:199]: Which might work. Is there a way to make this super clear to our users? I'm thinking about a user who may be an experienced developer, but new to docker. Would they know the difference between `docker compose` (the command in the terminal) and `Docker Compose` (the thing they're invoking with the above command(s))?

Is there a way to make this clear / remove ambiguity?

File: subo/command/compute_deploy_core.go (hunk 2 above)
Comment (callahad) [reply subo/command/compute_deploy_core.go]: Incorporated into 2413626bbb7b42a420943d6aaddb0ffcac23dfeb

**Review by javorszky — APPROVED** [review]
All good, we talked about the decisions behind all parts of it. 🚢

File: subo/command/compute_deploy_core.go (hunk 3 above)
Comment (callahad) [reply subo/command/compute_deploy_core.go]: Inclined to leave as-is: for most users, there is no distinction (`docker compose` is present on all Docker Desktop installs updated in the last year *and* `docker-compose` is shimmed to work like an alias to `docker compose`). Pointing out the historic separation gets nuanced enough that it may actually create confusion 😆

**Comment by callahad** [comment]
🙏 Thank you very much for the reviews
