### PR TITLE
fix(builder): Only run Javy once for JS/TS Runnables

### LINKED ISSUE #216: JS builder: Javy always run twice
The build script runs Javy and so does subo—only one needs to!

### PR DESCRIPTION
**Pull request by ospencer**
Closes #216

### CODE REVIEW

**Review by cohix — APPROVED** [review]

File: builder/context/native.go [hunk 1]
```diff
@@ -40,11 +40,9 @@ var nativeCommandsForLang = map[string]map[string][]string{
 		},
 		"typescript": {
 			"npm run build",
```
Comment (cohix) [inline builder/context/native.go:42]: Hmm, the `webpack` step is in a `prebuild` script... why does that run even though it's not being called?

Comment (ospencer) [reply builder/context/native.go:42]: Heh, I probably shouldn't bore you with all of the details of the lifecycles of npm scripts, but `pre` scripts get run before the script that shares a name with it; `prebuild` -> `build`. It's actually pretty handy for cases like this, where subo now only needs to worry about running the `build` command.
